force-app/main/default/objects/Lead/fields/HasValidatedEmail__c.field-meta.xml
<CustomField>
    <fullName>HasValidatedEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether the value in the Email field has been validated successfully</description>
    <inlineHelpText>Whether the value in the Email field has been validated successfully</inlineHelpText>
    <label>Validated Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ValidateEmailJobStatus__c.field-meta.xml
<CustomField>
    <fullName>ValidateEmailJobStatus__c</fullName>
    <defaultValue>'Not Started'</defaultValue>
    <label>Validate Email Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Enqueued</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProcessEvent__c/ProcessEvent__c.object-meta.xml
<CustomObject>
    <label>Process Event</label>
    <nameField>
        <displayFormat>PE-{0000000000}</displayFormat>
        <label>Process Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProcessEvent__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <label>End Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProcessEvent__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <label>Event Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessEvent__c/fields/ProcessName__c.field-meta.xml
<CustomField>
    <fullName>ProcessName__c</fullName>
    <label>Process Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProcessEvent__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>Start Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestService.cls
public virtual class TestService {

    public static Map<Type, TestService> instanceMap =
            new Map<Type, TestService>();

    public void assertJobStatusEquals(
            String expected, SObject record, Schema.SObjectField field,
            Type jobClass) {

        // Construct the message
        List<String> messageParts = new List<String> {
            jobClass.getName(),
            JSON.serialize(this.getLastProcessEvent(jobClass)),
            field.getDescribe().label
        };

        // Perform the assertion
        System.assertEquals(expected, record.get(field),
                String.join(messageParts, '|'));
    }

    public static TestService getInstance(Type serviceType) {

        // Get the instance from the cached map
        TestService instance = instanceMap.get(serviceType);

        // If the instance isn't already cached, instantiate a new instance
        // and then cache it
        if (instance == null) {
            instance = (TestService)serviceType.newInstance();
            instanceMap.put(serviceType, instance);
        }

        // Return the instance
        return instance;
    }

    public ProcessEvent__c getLastProcessEvent(Type jobClass) {
        List<ProcessEvent__c> events = [
            SELECT
                CreatedById,
                CreatedDate,
                EndTime__c,
                EventName__c,
                LastModifiedById,
                LastModifiedDate,
                Message__c,
                Name,
                ProcessName__c,
                Result__c,
                StartTime__c,
                Id
            FROM ProcessEvent__c
            WHERE ProcessName__c = :jobClass.getName()
            ORDER BY CreatedDate DESC
        ];

        return events.isEmpty() ? null : events[0];
    }

    public Lead getLead(String lastName) {
        return [
            SELECT
                Company,
                Email,
                FirstName,
                HasValidatedEmail__c,
                LastName,
                OwnerId,
                ValidateEmailJobStatus__c,
                Id
            FROM Lead
            WHERE LastName = :lastName
        ];
    }

    public class RuntimeException extends System.Exception {}
}